# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
#disqus: dbyll
#google_analytics: dbyll
title: mikelgb

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: mikelgb

description: Stylish Jekyll Theme
author:
  name: Mikel G. B.
  email: ginesborrasm@gmail.com
  github: mikelgb
  instagram: miquelgb
  #twitter: dbtek
  #pinterest: asd123
  #linkedin: asd123
  bio: Your stylish, minimalist theme!
  email_md5: 624d356097567ee912cae10597de2b55

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
