# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 5 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
#disqus: 
#google_analytics: 
title: mikelgb

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: mikelgb

description: Stylish Jekyll Theme
author:
  name: Mikel G. B.
  email: ginesborrasm@gmail.com
  github: mikelgb
  instagram: miquelgb
  #twitter: 
  #pinterest: 
  #linkedin: 
  bio: Site description!
  email_md5: 624d356097567ee912cae10597de2b55
  youtube: UCdPebbUb8f0RaCToEoeAb-Q

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
sidebar_background_image: http://simonandersonfitness.co.uk/wp-content/uploads/2013/05/bg-black-pattern.jpg

BASE_PATH:

plugins:
  - jekyll-paginate
