name:               "Mikel G. B."
description:        "Descripción"

url:                ""
author:             "mikelgb"
email:              "ginesborrasm@gmail.com"
gravatar_hash:      "624d356097567ee912cae10597de2b55"
#twitter:            ""
email:              "ginesborrasm@gmail.com"
github:             "mikelgb"
#pinterest:          ""
#linkedin:           ""
#facebook:           ""

disqus_shortname:   ""

background:         "http://simonandersonfitness.co.uk/wp-content/uploads/2013/05/bg-black-pattern.jpg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/about"
  - name:           "Download"
    href:           "/releases"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate
